---
label: Site - Settings
hide_body: true
fields:
- name: placeholder
  type: field_group
  config: {}
  fields:
  - name: placeholder
    type: include
    config: {}
    template: partial-image
    label: Placeholder Image
  label: Placeholder Image
  description: This image will appear on any image area that doesn't have an image
    assigned.
- name: fourOhFour
  type: field_group
  config: {}
  fields:
  - name: background_image
    type: field_group
    config: {}
    fields:
    - name: image
      type: include
      config: {}
      template: partial-image
      label: Image
    label: Background Image
  - name: copy
    type: include
    config: {}
    template: partial-text-group
    label: Copy
  label: '404'
- name: latest_news
  label: Latest News
  type: field_group
  fields:
  - name: three_column_cards
    type: include
    config: {}
    template: content-three-column-cards
    label: Three Column Cards
- name: latest_Events
  label: Latest Events
  type: field_group
  fields:
  - name: three_column_cards
    type: include
    config: {}
    template: content-three-column-cards
    label: Three Column Cards
- name: contact_info
  type: field_group_list
  fields:
  - name: individual_contact_info
    type: include
    config: {}
    template: partial-single-contact-info
    label: Individual Contact Info
  config:
    min: 
    max: 
    labelField: title
  label: Contact Info
- name: social_media
  type: field_group_list
  fields:
  - name: social_media
    type: include
    config: {}
    template: partial-social-media
    label: Social Media
  config:
    min: 
    max: 
    labelField: type
  label: Social Media List
- name: image_bar_above_footer
  type: field_group
  config: {}
  fields:
  - name: footer_image
    type: include
    config: {}
    template: partial-image
    label: Footer Image
  label: Image Bar Above Footer
- name: newsletter_kicker
  type: field_group
  config: {}
  fields:
  - name: text_content
    type: include
    config: {}
    template: partial-text-group
    label: Text Content
  label: Newsletter Kicker
pages:
- src/data/settings.json
